### ISSUE TITLE
invalid adress on self declared function

### ISSUE THREAD

**Issue by shibumi** [radare/radare2#2148]
Hello I have the following binary:

[https://paste.archlinux.de/kfu3n/](https://paste.archlinux.de/kfu3n/)

the binary is stripped. Its one of those 'crackme' games. I wanted to declare functions on the stripped binary. This worked pretty well with main at offset 0x0804867d:
```
af+ 0x0804867d 99 main
```
after this I can see the full function with: ``` pdf@main.```
I tried this with another function too. So i wanted to declare a function called check at offset 
0x80485b9:
```
af+ 0x80485b9 196 check
```
This worked too. But when I try pdf@check I get the following error:
```
Invalid address (check)
```
when I try pdf@0x80485b9 I get the disassembly of the function. The function is in the afl list too:

```
0x0804867d  99  0  main
0x08048400  34  1  entry0
0x08048388  6  1  sym.imp.__libc_start_main
0x0804838e  10  1  fcn.0804838e
0x08048384  10  1  fcn.08048384
0x08048398  6  1  sym.imp.scanf
0x0804839e  10  1  fcn.0804839e
0x080483a8  6  1  sym.imp.strlen
0x080483ae  10  1  fcn.080483ae
0x080483b8  6  1  sym.imp.printf
0x080483be  10  1  fcn.080483be
0x080483c8  6  1  sym.imp.sscanf
0x080483ce  10  1  fcn.080483ce
0x080483d8  6  1  sym.imp.strncmp
0x080483de  10  1  fcn.080483de
0x080483e8  6  1  sym.imp.exit
0x080483ee  10  1  fcn.080483ee
0x080483f8  42  1  sub.__libc_start_main_3f8
0x08048422  35  2  fcn.08048422
0x080485b9  196  0  check
```

afi says the following:

```
[0x080485ee]> afi check
#
 offset: 0x080485b9
 name: check
 size: 196
 call-convention: none
 cyclomatic-complexity: 0
 type: fcn [NEW]
 call-refs: 
 data-refs: 
 code-xrefs: 
 data-xrefs: 
 vars: 0
 diff: type: new
```
```
[0x080485ee]> afi main
#
 offset: 0x0804867d
 name: main
 size: 99
 call-convention: none
 cyclomatic-complexity: 0
 type: sym [NEW]
 call-refs: 
 data-refs: 
 code-xrefs: 
 data-xrefs: 
 vars: 0
 diff: type: new
```

Why has the main function the type 'sym' and the check function type 'fcn' ? The binary is stripped so the both should be 'fcn'.
