### ISSUE TITLE
Enhance RBin's VersionInfo implementation

### ISSUE THREAD

**Issue by radare** [radare/radare2#4216]
Almost working, I extract all version information for ELF binaries but now I need to store them in the sdb.

- [x] ELF version info extraction
- [x] PE version info extraction
- [ ] Mach-O version info extraction
- [ ] Store version info in sdb
- [ ] Retrieve version info from sdb in libr/core/bin.c and display them
- [ ] JSON output
- [ ] Test everything with radare2-regressions

**Comment by Maijin** [comment]
ping @0x2Adr1

**Comment by radare** [comment]
ping @0x2Adr1

**Comment by 0x2Adr1** [comment]
See https://github.com/radare/radare2/pull/4325

**Comment by radare** [comment]
`rabin2 -Vj` must be implemented at least. But this requires some refactoring. @0x2Adr1 are you up for this?

**Comment by 0x2Adr1** [comment]
yes, can it wait until next week ? Because I have some exams monday and tuesday :D

**Comment by radare** [comment]
Sure, just trying to organize issues for the next release

On 29 March 2016 at 15:41, Adrien Garin <notifications@github.com> wrote:

> yes, can it wait until next week ? Because I have some exams monday and
> tuesday :D
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4216#issuecomment-202898471>
>



-- 
--pancake

**Comment by alvarofe** [comment]
i could make the mach-0 version (0.10.3) since i will approach the ldid issue so why not spend time on this?

**Comment by radare** [comment]
ping? any chance to get this for 0.10.3?

**Comment by radare** [comment]
totally low prio

**Comment by Maijin** [comment]
Check this one @giuscri

**Comment by giuscri** [comment]
Current rabin2 output is
```
{"versioninfo":Version symbols section '.gnu.version' contains 9 entries:
 Addr: 0x000002fe  Offset: 0x000002fe  Link: 5 (.dynsym)
  0x00000000: 0 (*local*)
  0x00000002: (GLIBC_2.0)
  0x00000003: (GLIBC_2.1.3)
  0x00000004: (GLIBC_2.0)
  0x00000005: 0 (*local*)
  0x00000006: (GLIBC_2.0)
  0x00000007: 0 (*local*)
  0x00000008: 1 (*global*)


Version need section '.gnu.version_r' contains 1 entries:
 Addr: 0x00000310  Offset: 0x00000310  Link to section: 6 (.dynstr)
  0x00000000: Version: 1  File: libc.so.6  Cnt: 2
  0x00000010:   Name: GLIBC_2.1.3  Flags: none Version: 3
  0x00000020:   Name: GLIBC_2.0  Flags: none Version: 2
}
```

What's the schema you'd like to see implemented?

**Comment by Maijin** [comment]
Can you come on Telegram/IRC so we can brainstorm this ?

There is also PE version with a different output:

```
=== VS_VERSIONINFO ===

# VS_FIXEDFILEINFO

  Signature: 0xfeef04bd
  StrucVersion: 0xffffffff
  FileVersion: 65535.65535.65535.65535
  ProductVersion: 65535.65535.65535.65535
  FileFlagsMask: 0xffffffff
  FileFlags: 0x0
  FileOS: 0x0
  FileType: 0x0
  FileSubType: 0x0

# StringTable

  FileDescription: a PE with "standard" version info
  FileVersion: compulsory for version tab
  LegalCopyright: corkami.com
  StringFileInfo:
  Comments:
  CompanyName:
  InternalName:
  LegalTrademarks:
  OriginalFilename:
  PrivateBuild:
  ProductName:
  ProductVersion:
  SpecialBuild:
  :
   :
   ** EAT AT JOE"S **: best hamburger in town
  FileVersion: duplicates are authorized
```
