### ISSUE TITLE
Function argument issue (x86)

### ISSUE THREAD

**Issue by Dax89** [radare/radare2#6343]
Some commands doesn't retrieve function's arguments, for example in this function I have:

```
┌ (fcn) fcn.00401029 41
│   fcn.00401029 (int arg_8h, int arg_ch);
│           ; arg int arg_8h @ ebp+0x8
│           ; arg int arg_ch @ ebp+0xc
│           ; DATA XREF from 0x0040100e (entry0)
│           0x00401029      55             push ebp
│           0x0040102a      8bec           mov ebp, esp
│           0x0040102c      8b450c         mov eax, dword [ebp + arg_ch] ; [0xc:4]=0xffff
│           0x0040102f      83f810         cmp eax, 0x10
│       ┌─< 0x00401032      750c           jne 0x401040
│       │   0x00401034      6a00           push 0
│       │   0x00401036      ff7508         push dword [ebp + arg_8h]
│       │   0x00401039      e826000000     call sub.user32.dll_EndDialog_64; bool EndDialog(HWND hDlg, int nResult);
│      ┌──< 0x0040103e      eb09           jmp 0x401049
│      │└─> 0x00401040      b800000000     mov eax, 0
│      │    0x00401045      c9             leave
│      │    0x00401046      c21000         ret 0x10
│      │    ; JMP XREF from 0x0040103e (fcn.00401029)
│      └──> 0x00401049      b801000000     mov eax, 1
│           0x0040104e      c9             leave
└           0x0040104f      c21000         ret 0x10
```

If I call `afi` I get two arguments correctly:
```
[0x00401029]> afi
#
 offset: 0x00401029
 name: fcn.00401029
 size: 41
 realsz: 41
 stackframe: 0
 call-convention: cdecl
 cyclomatic-complexity: 1
 bits: 32
 type: fcn [NEW]
 num-bbs: 4
 edges: 3
 end-bbs: 2
 call-refs: 0x00401064 C
 data-refs:
 code-xrefs:
 in-degree: 0
 out-degree: 1
 data-xrefs:
 locals:0
 args: 2
arg int arg_8h @ ebp+0x8
arg int arg_ch @ ebp+0xc
 diff: type: new
```

but if I call `afij` I have `nargs = 0`:

```
[0x00401029]> afij
[{
    "offset": 4198441,
    "name": "fcn.00401029",
    "size": 41,
    "realsz": 41,
    "cc": 1,
    "nbbs": 4,
    "edges": 3,
    "ebbs": 2,
    "calltype": "cdecl",
    "type": "fcn",
    "diff": "NEW",
    "callrefs": [{
        "addr": 4198500,
        "type": "C",
        "at": 4198457
    }],
    "datarefs": [],
    "codexrefs": [],
    "dataxrefs": [],
    "difftype": "new",
    "indegree": 0,
    "outdegree": 1,
    "nargs": 0,
    "nlocals": 0
}]
```

Radare2's version:
```
radare2 1.1.0-git 13246 @ linux-x86-64 git.1.0.2-302-g4f418c9
commit: 4f418c979e71358b4804a0409524529874d3cbaa build: 2016-12-19
```

is this a known issue?
